
package com.le.flashsale.stock.dao;

import java.util.List;

import com.le.flashsale.stock.dto.StockDTO;
import com.le.flashsale.stock.dto.StockProductDTO;

public interface StockDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int insert(StockDTO stockDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int insertSelective(StockDTO stockDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    StockDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockDTO stockDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockDTO stockDTO);

    List<StockProductDTO> getAllStock();

    /**
     * 扣减库存
     *
     * @param stockId
     * @param num
     * @return
     */
    int deduceStockById(Long stockId, Integer num);
}