
package com.le.flashsale.mapper;

import java.util.List;

import com.le.flashsale.entity.ActivityInfoPO;

public interface ActivityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int insert(ActivityInfoPO activityInfoPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int insertSelective(ActivityInfoPO activityInfoPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    ActivityInfoPO selectByPrimaryKey(Long id);

    /**
     * 查询所有有效活动
     *
     * @return
     */
    List<ActivityInfoPO> selectAllEffectiveActivity();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityInfoPO activityInfoPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityInfoPO activityInfoPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int deduceNumsByPrimaryKey(Long id);


    int increaseNumsByPrimaryKey(Long id);
}