
package com.le.flashsale.mapper;

import com.le.flashsale.entity.OrderDetailPO;
import com.le.flashsale.entity.OrderPO;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    int insert(OrderPO orderPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    int insertSelective(OrderPO orderPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    OrderPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderPO orderPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderPO orderPO);

    /**
     * 根据订单号查询订单信息
     *
     * @param orderNo
     * @return
     */
    OrderDetailPO selectByOrderNo(String orderNo);
}