
package com.le.flashsale.mapper;

import java.util.List;

import com.le.flashsale.entity.ProductPO;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int insert(ProductPO productPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int insertSelective(ProductPO productPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    ProductPO selectByPrimaryKey(Long id);

    /**
     * 查询出所有未被删除的产品列表信息
     *
     * @return
     */
    List<ProductPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductPO productPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductPO productPO);
}