
package com.le.flashsale.mapper;

import java.util.List;

import com.le.flashsale.entity.StockPO;
import com.le.flashsale.entity.StockProductPO;

public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int insert(StockPO stockPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int insertSelective(StockPO stockPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    StockPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockPO stockPO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockPO stockPO);

    List<StockProductPO> getAllStock();

    /**
     * 扣减库存
     *
     * @param stockId
     * @param num
     * @return
     */
    int deduceStockById(Long stockId, Integer num);
}