
package com.le.flashsale.product.dao;

import java.util.List;

import com.le.flashsale.product.dto.ProductDTO;

public interface ProductDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int insert(ProductDTO productDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int insertSelective(ProductDTO productDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    ProductDTO selectByPrimaryKey(Long id);

    /**
     * 查询出所有未被删除的产品列表信息
     *
     * @return
     */
    List<ProductDTO> selectAll();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductDTO productDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductDTO productDTO);
}