
package com.le.flashsale.activity.dao;

import java.util.List;

import com.le.flashsale.activity.dto.ActivityInfoDTO;

public interface ActivityInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int insert(ActivityInfoDTO activityInfoDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int insertSelective(ActivityInfoDTO activityInfoDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    ActivityInfoDTO selectByPrimaryKey(Long id);

    /**
     * 查询所有有效的活动数据
     *
     * @return
     */
    List<ActivityInfoDTO> selectAllEffectiveActivity();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityInfoDTO activityInfoDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityInfoDTO activityInfoDTO);

    int deduceNumsByPrimaryKey(Long id);

    int increaseNumsByPrimaryKey(Long id);
}